spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: localhost
    password:
    port: 6379
thumbnail:
  width: 200
  height: 200

profile:
  file:
    path: /images/profile/
server:
  port: 8080

